In [78]:
import numpy as np
import pandas as pd
import torch
from torch.utils.data import Dataset, DataLoader
from sklearn.preprocessing import StandardScaler

# Load and pre-process data

In [111]:
target_col = "log_average_ms"

feature_cols = ["conv_flops", "matmul_flops",
                  "elementwise_mb", "reduction_mb", "normalization_mb",
                  "movement_mb", "memory_mb", "l1d_cache_kb",
                  "l1i_cache_kb", "l2_cache_kb", "base_clock_mhz",
                  "num_cores", "memory_bandwith_gbs"]

metadata_cols = ["model", "cpu_provider",
                 "machine_type", "platform", "run_id"]

In [112]:
# load test, train, val sets

train_df = pd.read_csv("train_set.csv")
val_df = pd.read_csv("val_set.csv")
test_df = pd.read_csv("test_set.csv")

print("train:", train_df.shape)
print("val:", val_df.shape)
print("test:", test_df.shape)

train: (100252, 154)
val: (21483, 154)
test: (21483, 154)

In [113]:
assert list(train_df.columns) == list(val_df.columns) == list(test_df.columns)

train_df.head()

,model,input_dimensions,input_dtypes,output_dimensions,output_dtypes,conv_flops,matmul_flops,elementwise_mb,reduction_mb,normalization_mb,...,base_clock_mhz,memory_bandwith_gbs,cpu_provider,machine_type,platform,repo_file,average_ms,stddev_ms,min_ms,max_ms
0,hardcorenas_d_Opset17_extended.onnx,x:1x3x224x224,x:float32,668:1x1000,668:float32,472440512,2560000,50.528229,5.204269,0.000000,...,2300.000,717,intel,xeon_plat,bluehive,hardcorenas_d_Opset17.onnx,14.069188,0.082284,13.931521,14.247209
1,vit_base_patch8_224_in21k_Opset17_disable_all....,x:1x3x224x224,x:float32,1089:1x21843,1089:float32,231211008,156097479168,1771.169711,0.000000,792.141724,...,2450.000,205,amd,epyc,gcloud,vit_base_patch8_224_in21k_Opset17.onnx,1481.456045,150.199862,1094.324125,1632.506909
2,tf_efficientnetv2_m_in21ft1k_Opset17_basic.onnx,x:1x3x384x384,x:float32,2466:1x1000,2466:float32,31470991360,2560000,1201.339462,67.736023,0.000000,...,2449.998,205,amd,epyc,gcloud,tf_efficientnetv2_m_in21ft1k_Opset17.onnx,301.127424,12.889699,286.464729,324.336829
3,shufflenet_v2_x1_5_Opset16.onnx,x:1x3x224x224,x:float32,1137:1x1000,1137:float32,266034528,2048000,8.246674,1.630875,0.000000,...,2449.998,205,amd,epyc,gcloud,shufflenet_v2_x1_5_Opset16.onnx,8.161246,0.036559,8.080030,8.197800
4,wide_resnet101_2_Opset16_timm.onnx,x:1x3x224x224,x:float32,971:1x1000,971:float32,45502005248,4096000,252.656250,4.218750,0.000000,...,2300.000,717,intel,xeon_plat,bluehive,wide_resnet101_2_Opset16_timm.onnx,38.147223,0.068437,38.035275,38.292409

In [114]:
# pre-processing function

def preprocess(df: pd.DataFrame, train=False) -> pd.DataFrame:

  #drop rows with missing features
  df = df.dropna(subset=["average_ms"])

  #remove rows with high standard deviation (only for train)
  cv_limit = 0.1 # 10% cv limit
  df["cv"] = df["stddev_ms"] / df["average_ms"]

  if train:
    df = df[df["cv"] <= cv_limit].copy()

  #add log_average_ms column
  df["log_average_ms"] = np.log(df["average_ms"])

  #remove decimals and round down
  for col in ["elementwise_mb", "reduction_mb", "normalization_mb", "movement_mb"]:
    df[col] = df[col].round(0)

  return df

In [115]:
train_df = preprocess(train_df, True)
test_df = preprocess(test_df, False)
val_df = preprocess(val_df, False)

print("train:", train_df.shape)
print("val:", val_df.shape)
print("test:", test_df.shape)

train: (95814, 156)
val: (21483, 156)
test: (21483, 156)

# Model Training

In [101]:
from xgboost import XGBRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

In [102]:
X_train = train_df[feature_cols]
y_train = train_df[target_col]

X_val = val_df[feature_cols]
y_val = val_df[target_col]

X_test = test_df[feature_cols]
y_test = test_df[target_col]

In [86]:
def rmse_log(y_true, y_pred):
  return np.sqrt(mean_squared_error(y_true, y_pred))

In [87]:
def train_xgb(params, X_train, y_train, X_val, y_val):
  model = XGBRegressor(
      objective="reg:squarederror",
      tree_method="hist",
      eval_metric="rmse",
      random_state=67,
      n_jobs=-1,
      early_stopping_rounds=100,
      **params,
  )

  model.fit(
      X_train,
      y_train,
      eval_set=[(X_val, y_val)],
      verbose=100,
  )

  val_pred = model.predict(X_val)
  score = rmse_log(y_val, val_pred)

  return model, score

In [126]:
from sklearn.model_selection import ParameterSampler

param_dist = {
    "n_estimators": [1800, 2000, 2400, 2800, 3000, 3500, 4000, 5000],
    "learning_rate": [0.025, 0.03, 0.04, 0.05, 0.06, 0.08],
    "max_depth": [5, 6, 7, 8],
    "min_child_weight": [3, 5, 8, 10, 15, 20, 30],
    "subsample": [0.85, 0.9, 0.95, 1.0],
    "colsample_bytree": [0.8, 0.85, 0.9, 0.95, 1.0],
    "reg_lambda": [0.5, 1.0, 2.0, 3.0, 5.0, 10.0, 20.0],
    "reg_alpha": [0.0, 0.05, 0.1, 0.3, 0.5, 1.0, 2.0],
}

In [125]:
manual_params = [
    {
        "n_estimators": 2000,
        "learning_rate": 0.08,
        "max_depth": 7,
        "min_child_weight": 10,
        "subsample": 1.0,
        "colsample_bytree": 0.9,
        "reg_lambda": 1.0,
        "reg_alpha": 1.0,
    },
    {
        "n_estimators": 2400,
        "learning_rate": 0.06,
        "max_depth": 7,
        "min_child_weight": 10,
        "subsample": 1.0,
        "colsample_bytree": 0.9,
        "reg_lambda": 1.0,
        "reg_alpha": 1.0,
    },
    {
        "n_estimators": 1800,
        "learning_rate": 0.10,
        "max_depth": 7,
        "min_child_weight": 10,
        "subsample": 1.0,
        "colsample_bytree": 0.9,
        "reg_lambda": 1.0,
        "reg_alpha": 1.0,
    },
    {
        "n_estimators": 2200,
        "learning_rate": 0.08,
        "max_depth": 8,
        "min_child_weight": 15,
        "subsample": 1.0,
        "colsample_bytree": 0.9,
        "reg_lambda": 1.0,
        "reg_alpha": 1.0,
    },
    {
        "n_estimators": 2000,
        "learning_rate": 0.08,
        "max_depth": 7,
        "min_child_weight": 10,
        "subsample": 0.95,
        "colsample_bytree": 0.9,
        "reg_lambda": 1.0,
        "reg_alpha": 1.0,
    },
]

In [127]:
sampled_params = manual_params + list(ParameterSampler(
    param_dist,
    n_iter=60,
    random_state=67,
))

results = []

best_model = None
best_score = float("inf")
best_params = None

for i, params in enumerate(sampled_params, start=1):
  model, val_rmse = train_xgb(params, X_train, y_train, X_val, y_val)

  row = {
        "run": i,
        "val_rmse_log": val_rmse,
        **params,
    }

  results.append(row)

  if val_rmse < best_score:
    best_score = val_rmse
    best_model = model
    best_params = params

  print(f"{i:02d} | val RMSE log = {val_rmse:.5f} | best = {best_score:.5f}")


tuning_results = pd.DataFrame(results).sort_values("val_rmse_log")
tuning_results.head(10)

[0]	validation_0-rmse:1.38362
[100]	validation_0-rmse:0.37875
[200]	validation_0-rmse:0.32042
[300]	validation_0-rmse:0.30158
[400]	validation_0-rmse:0.29546
[500]	validation_0-rmse:0.29257
[600]	validation_0-rmse:0.29101
[700]	validation_0-rmse:0.29005
[800]	validation_0-rmse:0.28952
[900]	validation_0-rmse:0.28906
[1000]	validation_0-rmse:0.28891
[1100]	validation_0-rmse:0.28880
[1200]	validation_0-rmse:0.28878
[1300]	validation_0-rmse:0.28873
[1400]	validation_0-rmse:0.28885
[1430]	validation_0-rmse:0.28889
01 | val RMSE log = 0.28872 | best = 0.28872
[0]	validation_0-rmse:1.40681
[100]	validation_0-rmse:0.40912
[200]	validation_0-rmse:0.34261
[300]	validation_0-rmse:0.31544
[400]	validation_0-rmse:0.30247
[500]	validation_0-rmse:0.29645
[600]	validation_0-rmse:0.29377
[700]	validation_0-rmse:0.29221
[800]	validation_0-rmse:0.29101
[900]	validation_0-rmse:0.29028
[1000]	validation_0-rmse:0.28970
[1100]	validation_0-rmse:0.28931
[1200]	validation_0-rmse:0.28898
[1300]	validation_0-rmse:0.28878
[1400]	validation_0-rmse:0.28873
[1500]	validation_0-rmse:0.28860
[1600]	validation_0-rmse:0.28859
[1700]	validation_0-rmse:0.28857
[1792]	validation_0-rmse:0.28863
02 | val RMSE log = 0.28855 | best = 0.28855
[0]	validation_0-rmse:1.36055
[100]	validation_0-rmse:0.35407
[200]	validation_0-rmse:0.30853
[300]	validation_0-rmse:0.29728
[400]	validation_0-rmse:0.29284
[500]	validation_0-rmse:0.29090
[600]	validation_0-rmse:0.28990
[700]	validation_0-rmse:0.28938
[800]	validation_0-rmse:0.28900
[900]	validation_0-rmse:0.28893
[1000]	validation_0-rmse:0.28894
[1042]	validation_0-rmse:0.28897
03 | val RMSE log = 0.28891 | best = 0.28855
[0]	validation_0-rmse:1.37863
[100]	validation_0-rmse:0.34139
[200]	validation_0-rmse:0.30375
[300]	validation_0-rmse:0.29479
[400]	validation_0-rmse:0.29120
[500]	validation_0-rmse:0.28983
[600]	validation_0-rmse:0.28929
[700]	validation_0-rmse:0.28908
[800]	validation_0-rmse:0.28901
[900]	validation_0-rmse:0.28906
[910]	validation_0-rmse:0.28908
04 | val RMSE log = 0.28899 | best = 0.28855
[0]	validation_0-rmse:1.38366
[100]	validation_0-rmse:0.37641
[200]	validation_0-rmse:0.32050
[300]	validation_0-rmse:0.30185
[400]	validation_0-rmse:0.29549
[500]	validation_0-rmse:0.29245
[600]	validation_0-rmse:0.29108
[700]	validation_0-rmse:0.29034
[800]	validation_0-rmse:0.29016
[900]	validation_0-rmse:0.29008
[1000]	validation_0-rmse:0.29020
[1007]	validation_0-rmse:0.29020
05 | val RMSE log = 0.29006 | best = 0.28855
[0]	validation_0-rmse:1.38714
[100]	validation_0-rmse:0.39737
[200]	validation_0-rmse:0.32982
[300]	validation_0-rmse:0.30747
[400]	validation_0-rmse:0.29925
[500]	validation_0-rmse:0.29446
[600]	validation_0-rmse:0.29216
[700]	validation_0-rmse:0.29091
[800]	validation_0-rmse:0.29024
[900]	validation_0-rmse:0.28985
[1000]	validation_0-rmse:0.28974
[1100]	validation_0-rmse:0.28975
[1114]	validation_0-rmse:0.28976
06 | val RMSE log = 0.28972 | best = 0.28855
[0]	validation_0-rmse:1.40705
[100]	validation_0-rmse:0.38321
[200]	validation_0-rmse:0.32971
[300]	validation_0-rmse:0.30700
[400]	validation_0-rmse:0.29785
[500]	validation_0-rmse:0.29362
[600]	validation_0-rmse:0.29175
[700]	validation_0-rmse:0.29083
[800]	validation_0-rmse:0.29065
[900]	validation_0-rmse:0.29062
[999]	validation_0-rmse:0.29086
07 | val RMSE log = 0.29061 | best = 0.28855
[0]	validation_0-rmse:1.41202
[100]	validation_0-rmse:0.46666
[200]	validation_0-rmse:0.37976
[300]	validation_0-rmse:0.34302
[400]	validation_0-rmse:0.32419
[500]	validation_0-rmse:0.31299
[600]	validation_0-rmse:0.30593
[700]	validation_0-rmse:0.30183
[800]	validation_0-rmse:0.29855
[900]	validation_0-rmse:0.29618
[1000]	validation_0-rmse:0.29460
[1100]	validation_0-rmse:0.29333
[1200]	validation_0-rmse:0.29230
[1300]	validation_0-rmse:0.29151
[1400]	validation_0-rmse:0.29096
[1500]	validation_0-rmse:0.29051
[1600]	validation_0-rmse:0.29027
[1700]	validation_0-rmse:0.29007
[1800]	validation_0-rmse:0.28993
[1900]	validation_0-rmse:0.28981
[2000]	validation_0-rmse:0.28973
[2100]	validation_0-rmse:0.28969
[2200]	validation_0-rmse:0.28970
[2208]	validation_0-rmse:0.28970
08 | val RMSE log = 0.28966 | best = 0.28855
[0]	validation_0-rmse:1.40679
[100]	validation_0-rmse:0.40718
[200]	validation_0-rmse:0.34295
[300]	validation_0-rmse:0.31563
[400]	validation_0-rmse:0.30327
[500]	validation_0-rmse:0.29725
[600]	validation_0-rmse:0.29439
[700]	validation_0-rmse:0.29250
[800]	validation_0-rmse:0.29152
[900]	validation_0-rmse:0.29082
[1000]	validation_0-rmse:0.29034
[1100]	validation_0-rmse:0.29013
[1200]	validation_0-rmse:0.28990
[1300]	validation_0-rmse:0.28986
[1400]	validation_0-rmse:0.28976
[1500]	validation_0-rmse:0.28972
[1565]	validation_0-rmse:0.28983
09 | val RMSE log = 0.28971 | best = 0.28855
[0]	validation_0-rmse:1.44443
[100]	validation_0-rmse:0.57796
[200]	validation_0-rmse:0.46973
[300]	validation_0-rmse:0.41839
[400]	validation_0-rmse:0.38101
[500]	validation_0-rmse:0.35586
[600]	validation_0-rmse:0.34029
[700]	validation_0-rmse:0.33086
[800]	validation_0-rmse:0.32279
[900]	validation_0-rmse:0.31726
[1000]	validation_0-rmse:0.31245
[1100]	validation_0-rmse:0.30821
[1200]	validation_0-rmse:0.30417
[1300]	validation_0-rmse:0.30197
[1400]	validation_0-rmse:0.30024
[1500]	validation_0-rmse:0.29846
[1600]	validation_0-rmse:0.29703
[1700]	validation_0-rmse:0.29604
[1799]	validation_0-rmse:0.29519
10 | val RMSE log = 0.29519 | best = 0.28855
[0]	validation_0-rmse:1.42787
[100]	validation_0-rmse:0.40771
[200]	validation_0-rmse:0.34574
[300]	validation_0-rmse:0.31843
[400]	validation_0-rmse:0.30704
[500]	validation_0-rmse:0.30012
[600]	validation_0-rmse:0.29658
[700]	validation_0-rmse:0.29407
[800]	validation_0-rmse:0.29286
[900]	validation_0-rmse:0.29214
[1000]	validation_0-rmse:0.29156
[1100]	validation_0-rmse:0.29115
[1200]	validation_0-rmse:0.29083
[1300]	validation_0-rmse:0.29056
[1400]	validation_0-rmse:0.29038
[1500]	validation_0-rmse:0.29023
[1600]	validation_0-rmse:0.29019
[1700]	validation_0-rmse:0.29013
[1800]	validation_0-rmse:0.29013
[1900]	validation_0-rmse:0.29014
[1925]	validation_0-rmse:0.29014
11 | val RMSE log = 0.29011 | best = 0.28855
[0]	validation_0-rmse:1.41535
[100]	validation_0-rmse:0.38573
[200]	validation_0-rmse:0.32765
[300]	validation_0-rmse:0.30731
[400]	validation_0-rmse:0.29815
[500]	validation_0-rmse:0.29395
[600]	validation_0-rmse:0.29195
[700]	validation_0-rmse:0.29066
[800]	validation_0-rmse:0.29000
[900]	validation_0-rmse:0.28952
[1000]	validation_0-rmse:0.28915
[1100]	validation_0-rmse:0.28886
[1200]	validation_0-rmse:0.28872
[1300]	validation_0-rmse:0.28864
[1400]	validation_0-rmse:0.28863
[1500]	validation_0-rmse:0.28858
[1600]	validation_0-rmse:0.28859
[1611]	validation_0-rmse:0.28859
12 | val RMSE log = 0.28858 | best = 0.28855
[0]	validation_0-rmse:1.42262
[100]	validation_0-rmse:0.49019
[200]	validation_0-rmse:0.39598
[300]	validation_0-rmse:0.35489
[400]	validation_0-rmse:0.33222
[500]	validation_0-rmse:0.31728
[600]	validation_0-rmse:0.30946
[700]	validation_0-rmse:0.30379
[800]	validation_0-rmse:0.29956
[900]	validation_0-rmse:0.29694
[1000]	validation_0-rmse:0.29492
[1100]	validation_0-rmse:0.29354
[1200]	validation_0-rmse:0.29238
[1300]	validation_0-rmse:0.29148
[1400]	validation_0-rmse:0.29091
[1500]	validation_0-rmse:0.29047
[1600]	validation_0-rmse:0.29020
[1700]	validation_0-rmse:0.29004
[1800]	validation_0-rmse:0.28995
[1900]	validation_0-rmse:0.28988
[2000]	validation_0-rmse:0.28980
[2100]	validation_0-rmse:0.28978
[2151]	validation_0-rmse:0.28981
13 | val RMSE log = 0.28976 | best = 0.28855
[0]	validation_0-rmse:1.44020
[100]	validation_0-rmse:0.45205
[200]	validation_0-rmse:0.36967
[300]	validation_0-rmse:0.33905
[400]	validation_0-rmse:0.31962
[500]	validation_0-rmse:0.30808
[600]	validation_0-rmse:0.30150
[700]	validation_0-rmse:0.29754
[800]	validation_0-rmse:0.29511
[900]	validation_0-rmse:0.29317
[1000]	validation_0-rmse:0.29193
[1100]	validation_0-rmse:0.29112
[1200]	validation_0-rmse:0.29050
[1300]	validation_0-rmse:0.29018
[1400]	validation_0-rmse:0.28996
[1500]	validation_0-rmse:0.28981
[1600]	validation_0-rmse:0.28971
[1700]	validation_0-rmse:0.28970
[1768]	validation_0-rmse:0.28970
14 | val RMSE log = 0.28968 | best = 0.28855
[0]	validation_0-rmse:1.38010
[100]	validation_0-rmse:0.34723
[200]	validation_0-rmse:0.30539
[300]	validation_0-rmse:0.29569
[400]	validation_0-rmse:0.29234
[500]	validation_0-rmse:0.29127
[600]	validation_0-rmse:0.29113
[700]	validation_0-rmse:0.29103
[800]	validation_0-rmse:0.29110
[808]	validation_0-rmse:0.29110
15 | val RMSE log = 0.29100 | best = 0.28855
[0]	validation_0-rmse:1.43883
[100]	validation_0-rmse:0.60876
[200]	validation_0-rmse:0.49704
[300]	validation_0-rmse:0.44278
[400]	validation_0-rmse:0.40822
[500]	validation_0-rmse:0.38249
[600]	validation_0-rmse:0.36678
[700]	validation_0-rmse:0.35294
[800]	validation_0-rmse:0.34395
[900]	validation_0-rmse:0.33658
[1000]	validation_0-rmse:0.32944
[1100]	validation_0-rmse:0.32382
[1200]	validation_0-rmse:0.31966
[1300]	validation_0-rmse:0.31566
[1400]	validation_0-rmse:0.31270
[1500]	validation_0-rmse:0.31003
[1600]	validation_0-rmse:0.30746
[1700]	validation_0-rmse:0.30606
[1800]	validation_0-rmse:0.30415
[1900]	validation_0-rmse:0.30271
[2000]	validation_0-rmse:0.30147
[2100]	validation_0-rmse:0.30002
[2200]	validation_0-rmse:0.29885
[2300]	validation_0-rmse:0.29790
[2400]	validation_0-rmse:0.29680
[2500]	validation_0-rmse:0.29616
[2600]	validation_0-rmse:0.29557
[2700]	validation_0-rmse:0.29499
[2800]	validation_0-rmse:0.29437
[2900]	validation_0-rmse:0.29387
[3000]	validation_0-rmse:0.29337
[3100]	validation_0-rmse:0.29292
[3200]	validation_0-rmse:0.29253
[3300]	validation_0-rmse:0.29208
[3400]	validation_0-rmse:0.29178
[3499]	validation_0-rmse:0.29154
16 | val RMSE log = 0.29154 | best = 0.28855
[0]	validation_0-rmse:1.41952
[100]	validation_0-rmse:0.52948
[200]	validation_0-rmse:0.42947
[300]	validation_0-rmse:0.38086
[400]	validation_0-rmse:0.35604
[500]	validation_0-rmse:0.33997
[600]	validation_0-rmse:0.32950
[700]	validation_0-rmse:0.32137
[800]	validation_0-rmse:0.31548
[900]	validation_0-rmse:0.31126
[1000]	validation_0-rmse:0.30784
[1100]	validation_0-rmse:0.30492
[1200]	validation_0-rmse:0.30274
[1300]	validation_0-rmse:0.30080
[1400]	validation_0-rmse:0.29911
[1500]	validation_0-rmse:0.29781
[1600]	validation_0-rmse:0.29673
[1700]	validation_0-rmse:0.29562
[1800]	validation_0-rmse:0.29479
[1900]	validation_0-rmse:0.29404
[2000]	validation_0-rmse:0.29329
[2100]	validation_0-rmse:0.29252
[2200]	validation_0-rmse:0.29200
[2300]	validation_0-rmse:0.29140
[2399]	validation_0-rmse:0.29089
17 | val RMSE log = 0.29089 | best = 0.28855
[0]	validation_0-rmse:1.44848
[100]	validation_0-rmse:0.65091
[200]	validation_0-rmse:0.53732
[300]	validation_0-rmse:0.48297
[400]	validation_0-rmse:0.44747
[500]	validation_0-rmse:0.42050
[600]	validation_0-rmse:0.39930
[700]	validation_0-rmse:0.38357
[800]	validation_0-rmse:0.36958
[900]	validation_0-rmse:0.35846
[1000]	validation_0-rmse:0.34945
[1100]	validation_0-rmse:0.34326
[1200]	validation_0-rmse:0.33696
[1300]	validation_0-rmse:0.33158
[1400]	validation_0-rmse:0.32763
[1500]	validation_0-rmse:0.32382
[1600]	validation_0-rmse:0.31979
[1700]	validation_0-rmse:0.31689
[1800]	validation_0-rmse:0.31435
[1900]	validation_0-rmse:0.31206
[2000]	validation_0-rmse:0.31024
[2100]	validation_0-rmse:0.30845
[2200]	validation_0-rmse:0.30689
[2300]	validation_0-rmse:0.30549
[2400]	validation_0-rmse:0.30409
[2500]	validation_0-rmse:0.30293
[2600]	validation_0-rmse:0.30187
[2700]	validation_0-rmse:0.30079
[2800]	validation_0-rmse:0.29986
[2900]	validation_0-rmse:0.29905
[3000]	validation_0-rmse:0.29823
[3100]	validation_0-rmse:0.29750
[3200]	validation_0-rmse:0.29688
[3300]	validation_0-rmse:0.29625
[3400]	validation_0-rmse:0.29571
[3500]	validation_0-rmse:0.29521
[3600]	validation_0-rmse:0.29465
[3700]	validation_0-rmse:0.29421
[3800]	validation_0-rmse:0.29379
[3900]	validation_0-rmse:0.29338
[4000]	validation_0-rmse:0.29300
[4100]	validation_0-rmse:0.29269
[4200]	validation_0-rmse:0.29238
[4300]	validation_0-rmse:0.29209
[4400]	validation_0-rmse:0.29184
[4500]	validation_0-rmse:0.29159
[4600]	validation_0-rmse:0.29138
[4700]	validation_0-rmse:0.29120
[4800]	validation_0-rmse:0.29101
[4900]	validation_0-rmse:0.29086
[4999]	validation_0-rmse:0.29070
18 | val RMSE log = 0.29070 | best = 0.28855
[0]	validation_0-rmse:1.42912
[100]	validation_0-rmse:0.56072
[200]	validation_0-rmse:0.45916
[300]	validation_0-rmse:0.41006
[400]	validation_0-rmse:0.37836
[500]	validation_0-rmse:0.35694
[600]	validation_0-rmse:0.34334
[700]	validation_0-rmse:0.33218
[800]	validation_0-rmse:0.32471
[900]	validation_0-rmse:0.31806
[1000]	validation_0-rmse:0.31387
[1100]	validation_0-rmse:0.31048
[1200]	validation_0-rmse:0.30683
[1300]	validation_0-rmse:0.30432
[1400]	validation_0-rmse:0.30221
[1500]	validation_0-rmse:0.30026
[1600]	validation_0-rmse:0.29875
[1700]	validation_0-rmse:0.29751
[1800]	validation_0-rmse:0.29632
[1900]	validation_0-rmse:0.29524
[2000]	validation_0-rmse:0.29449
[2100]	validation_0-rmse:0.29375
[2200]	validation_0-rmse:0.29315
[2300]	validation_0-rmse:0.29262
[2400]	validation_0-rmse:0.29212
[2500]	validation_0-rmse:0.29176
[2600]	validation_0-rmse:0.29141
[2700]	validation_0-rmse:0.29111
[2799]	validation_0-rmse:0.29083
19 | val RMSE log = 0.29083 | best = 0.28855
[0]	validation_0-rmse:1.38711
[100]	validation_0-rmse:0.38759
[200]	validation_0-rmse:0.32768
[300]	validation_0-rmse:0.30605
[400]	validation_0-rmse:0.29742
[500]	validation_0-rmse:0.29354
[600]	validation_0-rmse:0.29178
[700]	validation_0-rmse:0.29079
[800]	validation_0-rmse:0.29030
[900]	validation_0-rmse:0.29007
[1000]	validation_0-rmse:0.29010
[1027]	validation_0-rmse:0.29014
20 | val RMSE log = 0.29001 | best = 0.28855
[0]	validation_0-rmse:1.37987
[100]	validation_0-rmse:0.35033
[200]	validation_0-rmse:0.30944
[300]	validation_0-rmse:0.29734
[400]	validation_0-rmse:0.29298
[500]	validation_0-rmse:0.29080
[600]	validation_0-rmse:0.28998
[700]	validation_0-rmse:0.28966
[800]	validation_0-rmse:0.28959
[900]	validation_0-rmse:0.28958
[912]	validation_0-rmse:0.28959
21 | val RMSE log = 0.28955 | best = 0.28855
[0]	validation_0-rmse:1.44830
[100]	validation_0-rmse:0.65364
[200]	validation_0-rmse:0.53926
[300]	validation_0-rmse:0.48328
[400]	validation_0-rmse:0.44554
[500]	validation_0-rmse:0.41686
[600]	validation_0-rmse:0.39777
[700]	validation_0-rmse:0.38073
[800]	validation_0-rmse:0.36807
[900]	validation_0-rmse:0.35756
[1000]	validation_0-rmse:0.34904
[1100]	validation_0-rmse:0.34238
[1200]	validation_0-rmse:0.33658
[1300]	validation_0-rmse:0.33130
[1400]	validation_0-rmse:0.32712
[1500]	validation_0-rmse:0.32330
[1600]	validation_0-rmse:0.31993
[1700]	validation_0-rmse:0.31665
[1800]	validation_0-rmse:0.31404
[1900]	validation_0-rmse:0.31197
[2000]	validation_0-rmse:0.31017
[2100]	validation_0-rmse:0.30827
[2200]	validation_0-rmse:0.30671
[2300]	validation_0-rmse:0.30547
[2400]	validation_0-rmse:0.30422
[2500]	validation_0-rmse:0.30306
[2600]	validation_0-rmse:0.30199
[2700]	validation_0-rmse:0.30107
[2800]	validation_0-rmse:0.30002
[2900]	validation_0-rmse:0.29933
[2999]	validation_0-rmse:0.29862
22 | val RMSE log = 0.29862 | best = 0.28855
[0]	validation_0-rmse:1.42335
[100]	validation_0-rmse:0.50419
[200]	validation_0-rmse:0.40852
[300]	validation_0-rmse:0.36478
[400]	validation_0-rmse:0.33818
[500]	validation_0-rmse:0.32250
[600]	validation_0-rmse:0.31369
[700]	validation_0-rmse:0.30703
[800]	validation_0-rmse:0.30288
[900]	validation_0-rmse:0.29943
[1000]	validation_0-rmse:0.29702
[1100]	validation_0-rmse:0.29531
[1200]	validation_0-rmse:0.29376
[1300]	validation_0-rmse:0.29264
[1400]	validation_0-rmse:0.29183
[1500]	validation_0-rmse:0.29116
[1600]	validation_0-rmse:0.29070
[1700]	validation_0-rmse:0.29036
[1800]	validation_0-rmse:0.29008
[1900]	validation_0-rmse:0.28991
[2000]	validation_0-rmse:0.28982
[2100]	validation_0-rmse:0.28973
[2200]	validation_0-rmse:0.28967
[2300]	validation_0-rmse:0.28968
[2323]	validation_0-rmse:0.28970
23 | val RMSE log = 0.28963 | best = 0.28855
[0]	validation_0-rmse:1.40679
[100]	validation_0-rmse:0.39906
[200]	validation_0-rmse:0.33256
[300]	validation_0-rmse:0.30955
[400]	validation_0-rmse:0.29963
[500]	validation_0-rmse:0.29536
[600]	validation_0-rmse:0.29296
[700]	validation_0-rmse:0.29162
[800]	validation_0-rmse:0.29067
[900]	validation_0-rmse:0.29010
[1000]	validation_0-rmse:0.28964
[1100]	validation_0-rmse:0.28945
[1200]	validation_0-rmse:0.28943
[1251]	validation_0-rmse:0.28940
24 | val RMSE log = 0.28938 | best = 0.28855
[0]	validation_0-rmse:1.41842
[100]	validation_0-rmse:0.43565
[200]	validation_0-rmse:0.35656
[300]	validation_0-rmse:0.32449
[400]	validation_0-rmse:0.30914
[500]	validation_0-rmse:0.30156
[600]	validation_0-rmse:0.29743
[700]	validation_0-rmse:0.29477
[800]	validation_0-rmse:0.29304
[900]	validation_0-rmse:0.29200
[1000]	validation_0-rmse:0.29147
[1100]	validation_0-rmse:0.29099
[1200]	validation_0-rmse:0.29071
[1300]	validation_0-rmse:0.29056
[1400]	validation_0-rmse:0.29052
[1500]	validation_0-rmse:0.29049
[1577]	validation_0-rmse:0.29052
25 | val RMSE log = 0.29047 | best = 0.28855
[0]	validation_0-rmse:1.41945
[100]	validation_0-rmse:0.52022
[200]	validation_0-rmse:0.42376
[300]	validation_0-rmse:0.37749
[400]	validation_0-rmse:0.35367
[500]	validation_0-rmse:0.33526
[600]	validation_0-rmse:0.32495
[700]	validation_0-rmse:0.31727
[800]	validation_0-rmse:0.31141
[900]	validation_0-rmse:0.30685
[1000]	validation_0-rmse:0.30367
[1100]	validation_0-rmse:0.30101
[1200]	validation_0-rmse:0.29870
[1300]	validation_0-rmse:0.29688
[1400]	validation_0-rmse:0.29553
[1500]	validation_0-rmse:0.29445
[1600]	validation_0-rmse:0.29358
[1700]	validation_0-rmse:0.29286
[1800]	validation_0-rmse:0.29224
[1900]	validation_0-rmse:0.29174
[2000]	validation_0-rmse:0.29133
[2100]	validation_0-rmse:0.29102
[2200]	validation_0-rmse:0.29073
[2300]	validation_0-rmse:0.29057
[2400]	validation_0-rmse:0.29042
[2500]	validation_0-rmse:0.29030
[2600]	validation_0-rmse:0.29019
[2700]	validation_0-rmse:0.29019
[2800]	validation_0-rmse:0.29010
[2900]	validation_0-rmse:0.29005
[2958]	validation_0-rmse:0.29006
26 | val RMSE log = 0.29001 | best = 0.28855
[0]	validation_0-rmse:1.43862
[100]	validation_0-rmse:0.59955
[200]	validation_0-rmse:0.49621
[300]	validation_0-rmse:0.43919
[400]	validation_0-rmse:0.40175
[500]	validation_0-rmse:0.37871
[600]	validation_0-rmse:0.36259
[700]	validation_0-rmse:0.35090
[800]	validation_0-rmse:0.34084
[900]	validation_0-rmse:0.33288
[1000]	validation_0-rmse:0.32729
[1100]	validation_0-rmse:0.32263
[1200]	validation_0-rmse:0.31822
[1300]	validation_0-rmse:0.31430
[1400]	validation_0-rmse:0.31166
[1500]	validation_0-rmse:0.30894
[1600]	validation_0-rmse:0.30683
[1700]	validation_0-rmse:0.30487
[1800]	validation_0-rmse:0.30325
[1900]	validation_0-rmse:0.30181
[2000]	validation_0-rmse:0.30054
[2100]	validation_0-rmse:0.29931
[2200]	validation_0-rmse:0.29815
[2300]	validation_0-rmse:0.29735
[2399]	validation_0-rmse:0.29650
27 | val RMSE log = 0.29650 | best = 0.28855
[0]	validation_0-rmse:1.41868
[100]	validation_0-rmse:0.43044
[200]	validation_0-rmse:0.35444
[300]	validation_0-rmse:0.32253
[400]	validation_0-rmse:0.30770
[500]	validation_0-rmse:0.29982
[600]	validation_0-rmse:0.29556
[700]	validation_0-rmse:0.29319
[800]	validation_0-rmse:0.29185
[900]	validation_0-rmse:0.29104
[1000]	validation_0-rmse:0.29050
[1100]	validation_0-rmse:0.29021
[1200]	validation_0-rmse:0.29006
[1300]	validation_0-rmse:0.28996
[1400]	validation_0-rmse:0.28997
[1421]	validation_0-rmse:0.28998
28 | val RMSE log = 0.28993 | best = 0.28855
[0]	validation_0-rmse:1.38336
[100]	validation_0-rmse:0.37114
[200]	validation_0-rmse:0.31787
[300]	validation_0-rmse:0.30086
[400]	validation_0-rmse:0.29464
[500]	validation_0-rmse:0.29219
[600]	validation_0-rmse:0.29141
[700]	validation_0-rmse:0.29111
[800]	validation_0-rmse:0.29095
[900]	validation_0-rmse:0.29114

,run,val_rmse_log,n_estimators,learning_rate,max_depth,min_child_weight,subsample,colsample_bytree,reg_lambda,reg_alpha
1,2,0.288553,2400,0.060,7,10,1.00,0.90,1.0,1.00
11,12,0.288581,4000,0.050,8,8,1.00,0.90,0.5,2.00
0,1,0.288724,2000,0.080,7,10,1.00,0.90,1.0,1.00
2,3,0.288909,1800,0.100,7,10,1.00,0.90,1.0,1.00
43,44,0.288952,4000,0.025,7,30,1.00,0.95,2.0,0.10
3,4,0.288990,2200,0.080,8,15,1.00,0.90,1.0,1.00
42,43,0.289038,1800,0.080,7,20,1.00,0.90,1.0,0.30
52,53,0.289047,3000,0.060,7,30,1.00,0.85,3.0,0.05
47,48,0.289298,1800,0.060,7,5,1.00,1.00,10.0,0.05
55,56,0.289311,2400,0.080,7,10,0.95,0.90,3.0,2.00

# Evaluation

In [128]:
final_model = best_model

test_pred = final_model.predict(X_test)
test_rmse_log = np.sqrt(mean_squared_error(y_test, test_pred))

print("Test RMSE: ", test_rmse_log)

Test RMSE:  0.2825057870915487

In [129]:
def latency_metrics_from_log(y_log_true, y_log_pred):
    true_ms = np.exp(y_log_true)
    pred_ms = np.exp(y_log_pred)

    error_ms = pred_ms - true_ms
    rel_err = np.abs(error_ms) / true_ms
    ratio_err = np.maximum(pred_ms / true_ms, true_ms / pred_ms)

    rmse_log = np.sqrt(mean_squared_error(y_log_true, y_log_pred))
    rmse_ms = np.sqrt(np.mean(error_ms ** 2))
    rmse_percent = np.sqrt(np.mean(((error_ms / true_ms) * 100) ** 2))

    return {
        "rmse_log": rmse_log,
        "rmse_ms": rmse_ms,
        "rmse_percent": rmse_percent,

        "median_relative_error": np.median(rel_err),
        "p90_relative_error": np.percentile(rel_err, 90),
        "p95_relative_error": np.percentile(rel_err, 95),

        "median_percent_error": np.median(rel_err) * 100,
        "p90_percent_error": np.percentile(rel_err, 90) * 100,
        "p95_percent_error": np.percentile(rel_err, 95) * 100,

        "median_ratio_error": np.median(ratio_err),
        "p90_ratio_error": np.percentile(ratio_err, 90),

        "within_10pct": np.mean(rel_err <= 0.10),
        "within_25pct": np.mean(rel_err <= 0.25),
        "within_50pct": np.mean(rel_err <= 0.50),
        "within_2x": np.mean(ratio_err <= 2.0),
    }

In [130]:
val_metrics = latency_metrics_from_log(y_val, final_model.predict(X_val))
test_metrics = latency_metrics_from_log(y_test, final_model.predict(X_test))

pd.DataFrame([val_metrics, test_metrics], index=["val", "test"])

,rmse_log,rmse_ms,rmse_percent,median_relative_error,p90_relative_error,p95_relative_error,median_percent_error,p90_percent_error,p95_percent_error,median_ratio_error,p90_ratio_error,within_10pct,within_25pct,within_50pct,within_2x
val,0.288553,146.437448,39.259949,0.079280,0.413951,0.593755,7.928023,41.395085,59.375514,1.083104,1.524546,0.567472,0.812317,0.924731,0.957734
test,0.282506,132.612615,36.069926,0.078311,0.414712,0.590687,7.831146,41.471205,59.068737,1.081896,1.523052,0.572499,0.813853,0.926174,0.957967

# Analysis

In [106]:
test_results = test_df.copy()

test_results["pred_log_latency"] = test_pred
test_results["true_log_latency"] = y_test

test_results["pred_latency_ms"] = np.exp(test_results["pred_log_latency"])
test_results["true_latency_ms"] = np.exp(test_results["true_log_latency"])

test_results["relative_error"] = (
    np.abs(test_results["pred_latency_ms"] - test_results["true_latency_ms"])
    / test_results["true_latency_ms"]
)

In [109]:
def group_latency_metrics(g):
    y_true = g["true_log_latency"].to_numpy()
    y_pred = g["pred_log_latency"].to_numpy()

    true_ms = np.exp(y_true)
    pred_ms = np.exp(y_pred)

    rel_err = np.abs(pred_ms - true_ms) / true_ms

    return pd.Series({
        "count": len(g),
        "rmse_log": np.sqrt(mean_squared_error(y_true, y_pred)),
        "within_10pct": np.mean(rel_err <= 0.10),
        "within_25pct": np.mean(rel_err <= 0.25),
        "within_50pct": np.mean(rel_err <= 0.50),
    })

In [110]:
test_results.groupby("platform").apply(group_latency_metrics).reset_index()

/tmp/ipykernel_6910/3061731483.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  test_results.groupby("platform").apply(group_latency_metrics).reset_index()

   platform    count  rmse_log  within_10pct  within_25pct  within_50pct
0  bluehive  10744.0  0.325766      0.550168      0.778853      0.897710
1    gcloud  10739.0  0.230996      0.600056      0.852314      0.955955

In [119]:
test_results.groupby(["machine_type", "platform"]).apply(group_latency_metrics).reset_index()

/tmp/ipykernel_6910/2224414100.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  test_results.groupby(["machine_type", "platform"]).apply(group_latency_metrics).reset_index()

,machine_type,platform,count,rmse_log,within_10pct,within_25pct,within_50pct
0,epyc,gcloud,9388.0,0.204349,0.622816,0.873349,0.965914
1,xeon,gcloud,1351.0,0.366020,0.441895,0.706144,0.886751
2,xeon_plat,bluehive,10744.0,0.325766,0.550168,0.778853,0.897710

In [121]:
test_results.groupby(["cpu_provider", "platform"]).apply(group_latency_metrics).reset_index()

/tmp/ipykernel_6910/3658681541.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  test_results.groupby(["cpu_provider", "platform"]).apply(group_latency_metrics).reset_index()

,cpu_provider,platform,count,rmse_log,within_10pct,within_25pct,within_50pct
0,amd,gcloud,9388.0,0.204349,0.622816,0.873349,0.965914
1,intel,bluehive,10744.0,0.325766,0.550168,0.778853,0.897710
2,intel,gcloud,1351.0,0.366020,0.441895,0.706144,0.886751

In [122]:
test_results.groupby(["cpu_provider", "platform", "num_cores"]).apply(
    group_latency_metrics,
    include_groups=False
).reset_index()

,cpu_provider,platform,num_cores,count,rmse_log,within_10pct,within_25pct,within_50pct
0,amd,gcloud,1,2636.0,0.149715,0.753414,0.934750,0.980653
1,amd,gcloud,2,4015.0,0.195955,0.619925,0.884184,0.974595
2,amd,gcloud,4,2737.0,0.255572,0.501279,0.798319,0.938984
3,intel,bluehive,1,1347.0,0.241771,0.631032,0.881960,0.945805
4,intel,bluehive,2,2686.0,0.260675,0.656739,0.837305,0.931497
5,intel,bluehive,4,3999.0,0.317943,0.541385,0.775444,0.899725
6,intel,bluehive,8,2712.0,0.418367,0.417404,0.674779,0.837389
7,intel,gcloud,6,1351.0,0.366020,0.441895,0.706144,0.886751