In [ ]:
#pip install numpy pandas torch scikit-learn

WARNING: Cache entry deserialization failed, entry ignored
Collecting numpy
  Downloading numpy-2.4.4-cp314-cp314-macosx_14_0_arm64.whl.metadata (6.6 kB)
WARNING: Cache entry deserialization failed, entry ignored
Collecting pandas
  Downloading pandas-3.0.2-cp314-cp314-macosx_11_0_arm64.whl.metadata (79 kB)
WARNING: Cache entry deserialization failed, entry ignored
Collecting torch
  Downloading torch-2.11.0-cp314-cp314-macosx_11_0_arm64.whl.metadata (29 kB)
WARNING: Cache entry deserialization failed, entry ignored
Collecting scikit-learn
  Using cached scikit_learn-1.8.0-cp314-cp314-macosx_12_0_arm64.whl.metadata (11 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/sid-home/Projects/onnx-predict/.venv/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
WARNING: Cache entry deserialization failed, entry ignored
Collecting filelock (from torch)
  Downloading filelock-3.29.0-py3-none-any.whl.metadata (2.0 kB)
WARNING: Cache entry deserialization failed, entry ignored
Collecting typing-extensions>=4.10.0 (from torch)
  Using cached typing_extensions-4.15.0-py3-none-any.whl.metadata (3.3 kB)
WARNING: Cache entry deserialization failed, entry ignored
Collecting setuptools<82 (from torch)
  Downloading setuptools-81.0.0-py3-none-any.whl.metadata (6.6 kB)
WARNING: Cache entry deserialization failed, entry ignored
Collecting sympy>=1.13.3 (from torch)
  Downloading sympy-1.14.0-py3-none-any.whl.metadata (12 kB)
WARNING: Cache entry deserialization failed, entry ignored
Collecting networkx>=2.5.1 (from torch)
  Downloading networkx-3.6.1-py3-none-any.whl.metadata (6.8 kB)
WARNING: Cache entry deserialization failed, entry ignored
Collecting jinja2 (from torch)
  Using cached jinja2-3.1.6-py3-none-any.whl.metadata (2.9 kB)
WARNING: Cache entry deserialization failed, entry ignored
Collecting fsspec>=0.8.5 (from torch)
  Downloading fsspec-2026.3.0-py3-none-any.whl.metadata (10 kB)
WARNING: Cache entry deserialization failed, entry ignored
Collecting scipy>=1.10.0 (from scikit-learn)
  Downloading scipy-1.17.1-cp314-cp314-macosx_14_0_arm64.whl.metadata (62 kB)
WARNING: Cache entry deserialization failed, entry ignored
Collecting joblib>=1.3.0 (from scikit-learn)
  Using cached joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
WARNING: Cache entry deserialization failed, entry ignored
Collecting threadpoolctl>=3.2.0 (from scikit-learn)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: six>=1.5 in /Users/sid-home/Projects/onnx-predict/.venv/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
WARNING: Cache entry deserialization failed, entry ignored
Collecting mpmath<1.4,>=1.1.0 (from sympy>=1.13.3->torch)
  Using cached mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
WARNING: Cache entry deserialization failed, entry ignored
Collecting MarkupSafe>=2.0 (from jinja2->torch)
  Using cached markupsafe-3.0.3-cp314-cp314-macosx_11_0_arm64.whl.metadata (2.7 kB)
Downloading numpy-2.4.4-cp314-cp314-macosx_14_0_arm64.whl (5.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.2/5.2 MB 29.5 MB/s  0:00:00
Downloading pandas-3.0.2-cp314-cp314-macosx_11_0_arm64.whl (9.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.9/9.9 MB 31.3 MB/s  0:00:00 eta 0:00:01
Downloading torch-2.11.0-cp314-cp314-macosx_11_0_arm64.whl (80.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 80.6/80.6 MB 29.7 MB/s  0:00:02m0:00:0100:01
Downloading setuptools-81.0.0-py3-none-any.whl (1.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 24.8 MB/s  0:00:00
Using cached scikit_learn-1.8.0-cp314-cp314-macosx_12_0_arm64.whl (8.1 MB)
Downloading fsspec-2026.3.0-py3-none-any.whl (202 kB)
Using cached joblib-1.5.3-py3-none-any.whl (309 kB)
Downloading networkx-3.6.1-py3-none-any.whl (2.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 31.6 MB/s  0:00:00
Downloading scipy-1.17.1-cp314-cp314-macosx_14_0_arm64.whl (20.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 20.3/20.3 MB 25.2 MB/s  0:00:00 eta 0:00:01
Downloading sympy-1.14.0-py3-none-any.whl (6.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.3/6.3 MB 19.8 MB/s  0:00:00 eta 0:00:01
Using cached mpmath-1.3.0-py3-none-any.whl (536 kB)
Using cached threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Using cached typing_extensions-4.15.0-py3-none-any.whl (44 kB)
Downloading filelock-3.29.0-py3-none-any.whl (39 kB)
Using cached jinja2-3.1.6-py3-none-any.whl (134 kB)
Using cached markupsafe-3.0.3-cp314-cp314-macosx_11_0_arm64.whl (12 kB)
Installing collected packages: mpmath, typing-extensions, threadpoolctl, sympy, setuptools, numpy, networkx, MarkupSafe, joblib, fsspec, filelock, scipy, pandas, jinja2, torch, scikit-learn
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16/16 [scikit-learn][0m [scikit-learn]
Successfully installed MarkupSafe-3.0.3 filelock-3.29.0 fsspec-2026.3.0 jinja2-3.1.6 joblib-1.5.3 mpmath-1.3.0 networkx-3.6.1 numpy-2.4.4 pandas-3.0.2 scikit-learn-1.8.0 scipy-1.17.1 setuptools-81.0.0 sympy-1.14.0 threadpoolctl-3.6.0 torch-2.11.0 typing-extensions-4.15.0
Note: you may need to restart the kernel to use updated packages.

In [1]:
import numpy as np
import pandas as pd
import torch
from torch.utils.data import Dataset, DataLoader
from sklearn.preprocessing import StandardScaler

# Load and pre-process data

In [2]:
target_col = "log_average_ms"

feature_cols = ["conv_flops", "matmul_flops",
                  "elementwise_mb", "reduction_mb", "normalization_mb",
                  "movement_mb", "memory_mb", "l1d_cache_kb",
                  "l1i_cache_kb", "l2_cache_kb", "base_clock_mhz",
                  "num_cores", "memory_bandwith_gbs", 
                  "total_flops", "total_mb", "arithmetic_intensity",
                  "flops_per_core", "movement_frac_x_cores"]

metadata_cols = ["model", "cpu_provider",
                 "machine_type", "platform", "run_id"]

In [8]:
from google.colab import drive

drive.mount("/content/drive")

Mounted at /content/drive

In [10]:
# load test, train, val sets

train_df = pd.read_csv("/content/drive/MyDrive/Data/train_set.csv")
val_df = pd.read_csv("/content/drive/MyDrive/Data/val_set.csv")
test_df = pd.read_csv("/content/drive/MyDrive/Data/test_set.csv")

print("train:", train_df.shape)
print("val:", val_df.shape)
print("test:", test_df.shape)

train: (100252, 154)
val: (21483, 154)
test: (21483, 154)

In [11]:
assert list(train_df.columns) == list(val_df.columns) == list(test_df.columns)

train_df.head()

,model,input_dimensions,input_dtypes,output_dimensions,output_dtypes,conv_flops,matmul_flops,elementwise_mb,reduction_mb,normalization_mb,...,base_clock_mhz,memory_bandwith_gbs,cpu_provider,machine_type,platform,repo_file,average_ms,stddev_ms,min_ms,max_ms
0,hardcorenas_d_Opset17_extended.onnx,x:1x3x224x224,x:float32,668:1x1000,668:float32,472440512,2560000,50.528229,5.204269,0.000000,...,2300.000,717,intel,xeon_plat,bluehive,hardcorenas_d_Opset17.onnx,14.069188,0.082284,13.931521,14.247209
1,vit_base_patch8_224_in21k_Opset17_disable_all....,x:1x3x224x224,x:float32,1089:1x21843,1089:float32,231211008,156097479168,1771.169711,0.000000,792.141724,...,2450.000,205,amd,epyc,gcloud,vit_base_patch8_224_in21k_Opset17.onnx,1481.456045,150.199862,1094.324125,1632.506909
2,tf_efficientnetv2_m_in21ft1k_Opset17_basic.onnx,x:1x3x384x384,x:float32,2466:1x1000,2466:float32,31470991360,2560000,1201.339462,67.736023,0.000000,...,2449.998,205,amd,epyc,gcloud,tf_efficientnetv2_m_in21ft1k_Opset17.onnx,301.127424,12.889699,286.464729,324.336829
3,shufflenet_v2_x1_5_Opset16.onnx,x:1x3x224x224,x:float32,1137:1x1000,1137:float32,266034528,2048000,8.246674,1.630875,0.000000,...,2449.998,205,amd,epyc,gcloud,shufflenet_v2_x1_5_Opset16.onnx,8.161246,0.036559,8.080030,8.197800
4,wide_resnet101_2_Opset16_timm.onnx,x:1x3x224x224,x:float32,971:1x1000,971:float32,45502005248,4096000,252.656250,4.218750,0.000000,...,2300.000,717,intel,xeon_plat,bluehive,wide_resnet101_2_Opset16_timm.onnx,38.147223,0.068437,38.035275,38.292409

In [12]:
# pre-processing function

def preprocess(df: pd.DataFrame, train=False) -> pd.DataFrame:

  #drop rows with missing features
  df = df.dropna(subset=["average_ms"])

  #remove rows with high standard deviation (only for train)
  cv_limit = 0.1 # 10% cv limit
  df["cv"] = df["stddev_ms"] / df["average_ms"]

  if train:
    df = df[df["cv"] <= cv_limit].copy()

  #add log_average_ms column
  df["log_average_ms"] = np.log(df["average_ms"])

  #remove decimals and round down
  for col in ["elementwise_mb", "reduction_mb", "normalization_mb", "movement_mb"]:
    df[col] = df[col].round(0)
  
  eps = 1e-9
  cores = df["num_cores"].clip(lower=1)
  
  df["total_flops"] = df["conv_flops"] + df["matmul_flops"]

  df["total_mb"] = (
      df["elementwise_mb"]
      + df["reduction_mb"]
      + df["movement_mb"]
  )

  df["arithmetic_intensity"] = df["total_flops"] / (df["total_mb"] + eps)

  df["flops_per_core"] = df["total_flops"] / cores

  df["movement_frac_x_cores"] = (df["movement_mb"] / (df["total_mb"] + eps)) * cores

  return df

In [13]:
train_df = preprocess(train_df, True)
test_df = preprocess(test_df, False)
val_df = preprocess(val_df, False)

print("train:", train_df.shape)
print("val:", val_df.shape)
print("test:", test_df.shape)

train: (95814, 161)
val: (21483, 161)
test: (21483, 161)

# Model Training

In [ ]:
#pip install xgboost

Collecting xgboost
  Downloading xgboost-3.2.0-py3-none-macosx_12_0_arm64.whl.metadata (2.1 kB)
Requirement already satisfied: numpy in /Users/sid-home/Projects/onnx-predict/.venv/lib/python3.14/site-packages (from xgboost) (2.4.4)
Requirement already satisfied: scipy in /Users/sid-home/Projects/onnx-predict/.venv/lib/python3.14/site-packages (from xgboost) (1.17.1)
Downloading xgboost-3.2.0-py3-none-macosx_12_0_arm64.whl (2.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.3/2.3 MB 5.3 MB/s  0:00:00 eta 0:00:01
Installing collected packages: xgboost
Successfully installed xgboost-3.2.0
Note: you may need to restart the kernel to use updated packages.

In [14]:
from xgboost import XGBRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

In [15]:
X_train = train_df[feature_cols]
y_train = train_df[target_col]

X_val = val_df[feature_cols]
y_val = val_df[target_col]

X_test = test_df[feature_cols]
y_test = test_df[target_col]

In [16]:
def rmse_log(y_true, y_pred):
  return np.sqrt(mean_squared_error(y_true, y_pred))

In [17]:
def train_xgb(params, X_train, y_train, X_val, y_val):
  model = XGBRegressor(
      objective="reg:squarederror",
      tree_method="hist",
      eval_metric="rmse",
      random_state=67,
      n_jobs=-1,
      early_stopping_rounds=100,
      **params,
  )

  model.fit(
      X_train,
      y_train,
      eval_set=[(X_val, y_val)],
      verbose=100,
  )

  val_pred = model.predict(X_val)
  score = rmse_log(y_val, val_pred)

  return model, score

In [21]:
from sklearn.model_selection import ParameterSampler

param_dist = {
    "n_estimators": [500, 800, 1200, 1600, 2000, 2500, 3000, 4000, 5000],
    "learning_rate": [0.005, 0.01, 0.02, 0.03, 0.05, 0.08, 0.10, 0.15],
    "max_depth": [3, 4, 5, 6, 7, 8, 10],
    "min_child_weight": [1, 2, 3, 5, 8, 10, 15, 20, 30, 50],
    "subsample": [0.6, 0.7, 0.8, 0.9, 1.0],
    "colsample_bytree": [0.6, 0.7, 0.8, 0.9, 1.0],
    "reg_lambda": [0.0, 0.1, 0.5, 1.0, 3.0, 5.0, 10.0, 20.0, 50.0],
    "reg_alpha": [0.0, 0.001, 0.01, 0.05, 0.1, 0.5, 1.0, 2.0, 5.0],
}

In [35]:
# sampled_params = list(ParameterSampler(
#     param_dist,
#     n_iter=60,
#     random_state=67,
# ))

# results = []

# best_model = None
# best_score = float("inf")
# best_params = None

for i, params in enumerate(sampled_params, start=58):
  model, val_rmse = train_xgb(params, X_train, y_train, X_val, y_val)

  row = {
        "run": i,
        "val_rmse_log": val_rmse,
        **params,
    }

  results.append(row)

  if val_rmse < best_score:
    best_score = val_rmse
    best_model = model
    best_params = params

  print(f"{i:02d} | val RMSE log = {val_rmse:.5f} | best = {best_score:.5f}")


tuning_results = pd.DataFrame(results).sort_values("val_rmse_log")
tuning_results.head(10)

[0]	validation_0-rmse:1.28454
[100]	validation_0-rmse:0.29113
[200]	validation_0-rmse:0.28974
[294]	validation_0-rmse:0.29066
58 | val RMSE log = 0.28974 | best = 0.28853
[0]	validation_0-rmse:1.43803
[100]	validation_0-rmse:0.35610
[200]	validation_0-rmse:0.30817
[300]	validation_0-rmse:0.29646
[400]	validation_0-rmse:0.29211
[500]	validation_0-rmse:0.29080
[600]	validation_0-rmse:0.29046
[700]	validation_0-rmse:0.29042
[778]	validation_0-rmse:0.29045
59 | val RMSE log = 0.29035 | best = 0.28853
[0]	validation_0-rmse:1.35953
[100]	validation_0-rmse:0.34018
[200]	validation_0-rmse:0.30628
[300]	validation_0-rmse:0.29755
[400]	validation_0-rmse:0.29430
[500]	validation_0-rmse:0.29304
[600]	validation_0-rmse:0.29220
[700]	validation_0-rmse:0.29154
[800]	validation_0-rmse:0.29153
[872]	validation_0-rmse:0.29169
60 | val RMSE log = 0.29141 | best = 0.28853
[0]	validation_0-rmse:1.30259
[100]	validation_0-rmse:0.31175
[200]	validation_0-rmse:0.29384
[300]	validation_0-rmse:0.29141
[400]	validation_0-rmse:0.29147
[442]	validation_0-rmse:0.29164
61 | val RMSE log = 0.29114 | best = 0.28853
[0]	validation_0-rmse:1.39516
[100]	validation_0-rmse:0.44212
[200]	validation_0-rmse:0.37226
[300]	validation_0-rmse:0.34142
[400]	validation_0-rmse:0.32556
[500]	validation_0-rmse:0.31612
[600]	validation_0-rmse:0.31019
[700]	validation_0-rmse:0.30548
[800]	validation_0-rmse:0.30272
[900]	validation_0-rmse:0.30057
[1000]	validation_0-rmse:0.29929
[1100]	validation_0-rmse:0.29803
[1200]	validation_0-rmse:0.29689
[1300]	validation_0-rmse:0.29592
[1400]	validation_0-rmse:0.29540
[1500]	validation_0-rmse:0.29473
[1600]	validation_0-rmse:0.29457
[1700]	validation_0-rmse:0.29412
[1800]	validation_0-rmse:0.29388
[1900]	validation_0-rmse:0.29373
[2000]	validation_0-rmse:0.29355
[2100]	validation_0-rmse:0.29349
[2200]	validation_0-rmse:0.29344
[2227]	validation_0-rmse:0.29345
62 | val RMSE log = 0.29331 | best = 0.28853
[0]	validation_0-rmse:1.40026
[100]	validation_0-rmse:0.48250
[200]	validation_0-rmse:0.40644
[300]	validation_0-rmse:0.37058
[400]	validation_0-rmse:0.35252
[500]	validation_0-rmse:0.33835
[600]	validation_0-rmse:0.32810
[700]	validation_0-rmse:0.32138
[800]	validation_0-rmse:0.31614
[900]	validation_0-rmse:0.31186
[1000]	validation_0-rmse:0.30878
[1100]	validation_0-rmse:0.30660
[1200]	validation_0-rmse:0.30460
[1300]	validation_0-rmse:0.30261
[1400]	validation_0-rmse:0.30122
[1500]	validation_0-rmse:0.30011
[1600]	validation_0-rmse:0.29916
[1700]	validation_0-rmse:0.29816
[1800]	validation_0-rmse:0.29729
[1900]	validation_0-rmse:0.29667
[2000]	validation_0-rmse:0.29605
[2100]	validation_0-rmse:0.29565
[2200]	validation_0-rmse:0.29524
[2300]	validation_0-rmse:0.29487
[2400]	validation_0-rmse:0.29446
[2500]	validation_0-rmse:0.29412
[2600]	validation_0-rmse:0.29394
[2700]	validation_0-rmse:0.29360
[2800]	validation_0-rmse:0.29332
[2900]	validation_0-rmse:0.29321
[3000]	validation_0-rmse:0.29298
[3100]	validation_0-rmse:0.29279
[3200]	validation_0-rmse:0.29273
[3300]	validation_0-rmse:0.29268
[3400]	validation_0-rmse:0.29250
[3500]	validation_0-rmse:0.29246
[3600]	validation_0-rmse:0.29237
[3700]	validation_0-rmse:0.29223
[3800]	validation_0-rmse:0.29208
[3900]	validation_0-rmse:0.29208
[3999]	validation_0-rmse:0.29191
63 | val RMSE log = 0.29190 | best = 0.28853
[0]	validation_0-rmse:1.39114
[100]	validation_0-rmse:0.40567
[200]	validation_0-rmse:0.34793
[300]	validation_0-rmse:0.32420
[400]	validation_0-rmse:0.31141
[500]	validation_0-rmse:0.30453
[600]	validation_0-rmse:0.30033
[700]	validation_0-rmse:0.29735
[800]	validation_0-rmse:0.29575
[900]	validation_0-rmse:0.29463
[1000]	validation_0-rmse:0.29394
[1100]	validation_0-rmse:0.29318
[1200]	validation_0-rmse:0.29268
[1300]	validation_0-rmse:0.29230
[1400]	validation_0-rmse:0.29201
[1500]	validation_0-rmse:0.29183
[1600]	validation_0-rmse:0.29177
[1700]	validation_0-rmse:0.29168
[1800]	validation_0-rmse:0.29158
[1870]	validation_0-rmse:0.29156
64 | val RMSE log = 0.29149 | best = 0.28853
[0]	validation_0-rmse:1.38149
[100]	validation_0-rmse:0.46765
[200]	validation_0-rmse:0.39917
[300]	validation_0-rmse:0.36807
[400]	validation_0-rmse:0.34562
[500]	validation_0-rmse:0.33269
[600]	validation_0-rmse:0.32297
[700]	validation_0-rmse:0.31623
[800]	validation_0-rmse:0.31179
[900]	validation_0-rmse:0.30817
[1000]	validation_0-rmse:0.30541
[1100]	validation_0-rmse:0.30326
[1200]	validation_0-rmse:0.30120
[1300]	validation_0-rmse:0.29957
[1400]	validation_0-rmse:0.29816
[1500]	validation_0-rmse:0.29708
[1600]	validation_0-rmse:0.29606
[1700]	validation_0-rmse:0.29514
[1800]	validation_0-rmse:0.29442
[1900]	validation_0-rmse:0.29368
[2000]	validation_0-rmse:0.29302
[2100]	validation_0-rmse:0.29240
[2200]	validation_0-rmse:0.29191
[2300]	validation_0-rmse:0.29155
[2400]	validation_0-rmse:0.29123
[2499]	validation_0-rmse:0.29090
65 | val RMSE log = 0.29090 | best = 0.28853
[0]	validation_0-rmse:1.45423
[100]	validation_0-rmse:0.48988
[200]	validation_0-rmse:0.37112
[300]	validation_0-rmse:0.33413
[400]	validation_0-rmse:0.31666
[500]	validation_0-rmse:0.30592
[600]	validation_0-rmse:0.29972
[700]	validation_0-rmse:0.29612
[800]	validation_0-rmse:0.29435
[900]	validation_0-rmse:0.29297
[1000]	validation_0-rmse:0.29239
[1100]	validation_0-rmse:0.29201
[1200]	validation_0-rmse:0.29170
[1300]	validation_0-rmse:0.29161
[1400]	validation_0-rmse:0.29167
[1411]	validation_0-rmse:0.29166
66 | val RMSE log = 0.29158 | best = 0.28853
[0]	validation_0-rmse:1.44972
[100]	validation_0-rmse:0.73855
[200]	validation_0-rmse:0.62092
[300]	validation_0-rmse:0.56372
[400]	validation_0-rmse:0.52496
[499]	validation_0-rmse:0.50103
67 | val RMSE log = 0.50103 | best = 0.28853
[0]	validation_0-rmse:1.47190
[100]	validation_0-rmse:1.08811
[200]	validation_0-rmse:0.87172
[300]	validation_0-rmse:0.74858
[400]	validation_0-rmse:0.67404
[500]	validation_0-rmse:0.62634
[600]	validation_0-rmse:0.59009
[700]	validation_0-rmse:0.56055
[800]	validation_0-rmse:0.53810
[900]	validation_0-rmse:0.51816
[1000]	validation_0-rmse:0.50022
[1100]	validation_0-rmse:0.48533
[1200]	validation_0-rmse:0.47238
[1300]	validation_0-rmse:0.46068
[1400]	validation_0-rmse:0.45131
[1500]	validation_0-rmse:0.44264
[1600]	validation_0-rmse:0.43572
[1700]	validation_0-rmse:0.42844
[1800]	validation_0-rmse:0.42185
[1900]	validation_0-rmse:0.41552
[2000]	validation_0-rmse:0.41010
[2100]	validation_0-rmse:0.40523
[2200]	validation_0-rmse:0.40038
[2300]	validation_0-rmse:0.39550
[2400]	validation_0-rmse:0.39157
[2500]	validation_0-rmse:0.38763
[2600]	validation_0-rmse:0.38382
[2700]	validation_0-rmse:0.38018
[2800]	validation_0-rmse:0.37687
[2900]	validation_0-rmse:0.37375
[3000]	validation_0-rmse:0.37068
[3100]	validation_0-rmse:0.36773
[3200]	validation_0-rmse:0.36501
[3300]	validation_0-rmse:0.36240
[3400]	validation_0-rmse:0.35983
[3500]	validation_0-rmse:0.35755
[3600]	validation_0-rmse:0.35526
[3700]	validation_0-rmse:0.35331
[3800]	validation_0-rmse:0.35112
[3900]	validation_0-rmse:0.34913
[4000]	validation_0-rmse:0.34730
[4100]	validation_0-rmse:0.34548
[4200]	validation_0-rmse:0.34370
[4300]	validation_0-rmse:0.34212
[4400]	validation_0-rmse:0.34047
[4500]	validation_0-rmse:0.33907
[4600]	validation_0-rmse:0.33754
[4700]	validation_0-rmse:0.33606
[4800]	validation_0-rmse:0.33461
[4900]	validation_0-rmse:0.33334
[4999]	validation_0-rmse:0.33205
68 | val RMSE log = 0.33205 | best = 0.28853
[0]	validation_0-rmse:1.47100
[100]	validation_0-rmse:1.01064
[200]	validation_0-rmse:0.74614
[300]	validation_0-rmse:0.59666
[400]	validation_0-rmse:0.50967
[500]	validation_0-rmse:0.45757
[600]	validation_0-rmse:0.42523
[700]	validation_0-rmse:0.40228
[800]	validation_0-rmse:0.38651
[900]	validation_0-rmse:0.37444
[1000]	validation_0-rmse:0.36426
[1100]	validation_0-rmse:0.35615
[1200]	validation_0-rmse:0.34885
[1300]	validation_0-rmse:0.34253
[1400]	validation_0-rmse:0.33681
[1500]	validation_0-rmse:0.33153
[1599]	validation_0-rmse:0.32754
69 | val RMSE log = 0.32754 | best = 0.28853
[0]	validation_0-rmse:1.45880
[100]	validation_0-rmse:0.81708
[200]	validation_0-rmse:0.69420
[300]	validation_0-rmse:0.62585
[400]	validation_0-rmse:0.57655
[500]	validation_0-rmse:0.54560
[600]	validation_0-rmse:0.52437
[700]	validation_0-rmse:0.50714
[800]	validation_0-rmse:0.49084
[900]	validation_0-rmse:0.47826
[1000]	validation_0-rmse:0.46866
[1100]	validation_0-rmse:0.45891
[1200]	validation_0-rmse:0.45045
[1300]	validation_0-rmse:0.44233
[1400]	validation_0-rmse:0.43510
[1500]	validation_0-rmse:0.42858
[1600]	validation_0-rmse:0.42250
[1700]	validation_0-rmse:0.41738
[1800]	validation_0-rmse:0.41250
[1900]	validation_0-rmse:0.40745
[2000]	validation_0-rmse:0.40304
[2100]	validation_0-rmse:0.39856
[2200]	validation_0-rmse:0.39476
[2300]	validation_0-rmse:0.39125
[2400]	validation_0-rmse:0.38775
[2500]	validation_0-rmse:0.38462
[2600]	validation_0-rmse:0.38163
[2700]	validation_0-rmse:0.37856
[2800]	validation_0-rmse:0.37604
[2900]	validation_0-rmse:0.37358
[3000]	validation_0-rmse:0.37132
[3100]	validation_0-rmse:0.36889
[3200]	validation_0-rmse:0.36673
[3300]	validation_0-rmse:0.36448
[3400]	validation_0-rmse:0.36242
[3500]	validation_0-rmse:0.36054
[3600]	validation_0-rmse:0.35873
[3700]	validation_0-rmse:0.35684
[3800]	validation_0-rmse:0.35523
[3900]	validation_0-rmse:0.35375
[4000]	validation_0-rmse:0.35228
[4100]	validation_0-rmse:0.35084
[4200]	validation_0-rmse:0.34942
[4300]	validation_0-rmse:0.34813
[4400]	validation_0-rmse:0.34689
[4500]	validation_0-rmse:0.34564
[4600]	validation_0-rmse:0.34441
[4700]	validation_0-rmse:0.34326
[4800]	validation_0-rmse:0.34209
[4900]	validation_0-rmse:0.34105
[4999]	validation_0-rmse:0.34000
70 | val RMSE log = 0.34000 | best = 0.28853
[0]	validation_0-rmse:1.45099
[100]	validation_0-rmse:0.42262
[200]	validation_0-rmse:0.32202
[300]	validation_0-rmse:0.30247
[400]	validation_0-rmse:0.29593
[500]	validation_0-rmse:0.29345
[600]	validation_0-rmse:0.29300
[700]	validation_0-rmse:0.29310
[728]	validation_0-rmse:0.29320
71 | val RMSE log = 0.29293 | best = 0.28853
[0]	validation_0-rmse:1.45483
[100]	validation_0-rmse:0.60567
[200]	validation_0-rmse:0.47500
[300]	validation_0-rmse:0.42135
[400]	validation_0-rmse:0.38754
[500]	validation_0-rmse:0.36633
[600]	validation_0-rmse:0.35010
[700]	validation_0-rmse:0.33892
[799]	validation_0-rmse:0.33091
72 | val RMSE log = 0.33091 | best = 0.28853
[0]	validation_0-rmse:1.38985
[100]	validation_0-rmse:0.35505
[200]	validation_0-rmse:0.31380
[300]	validation_0-rmse:0.30153
[400]	validation_0-rmse:0.29649
[500]	validation_0-rmse:0.29431
[600]	validation_0-rmse:0.29296
[700]	validation_0-rmse:0.29189
[800]	validation_0-rmse:0.29162
[900]	validation_0-rmse:0.29125
[1000]	validation_0-rmse:0.29097
[1100]	validation_0-rmse:0.29082
[1199]	validation_0-rmse:0.29090
73 | val RMSE log = 0.29064 | best = 0.28853
[0]	validation_0-rmse:1.46579
[100]	validation_0-rmse:0.81310
[200]	validation_0-rmse:0.59706
[300]	validation_0-rmse:0.51659
[400]	validation_0-rmse:0.47028
[500]	validation_0-rmse:0.43887
[600]	validation_0-rmse:0.41534
[700]	validation_0-rmse:0.39725
[800]	validation_0-rmse:0.38086
[900]	validation_0-rmse:0.36946
[1000]	validation_0-rmse:0.35927
[1100]	validation_0-rmse:0.35121
[1200]	validation_0-rmse:0.34496
[1300]	validation_0-rmse:0.33990
[1400]	validation_0-rmse:0.33494
[1500]	validation_0-rmse:0.33088
[1600]	validation_0-rmse:0.32710
[1700]	validation_0-rmse:0.32363
[1800]	validation_0-rmse:0.32016
[1900]	validation_0-rmse:0.31708
[2000]	validation_0-rmse:0.31482
[2100]	validation_0-rmse:0.31258
[2200]	validation_0-rmse:0.31081

KeyboardInterrupt:

# Evaluation

In [36]:
final_model = best_model

test_pred = final_model.predict(X_test)
test_rmse_log = np.sqrt(mean_squared_error(y_test, test_pred))

print("Test RMSE: ", test_rmse_log)

Test RMSE:  0.2834630431730758

In [37]:
def latency_metrics_from_log(y_log_true, y_log_pred):
    true_ms = np.exp(y_log_true)
    pred_ms = np.exp(y_log_pred)

    error_ms = pred_ms - true_ms
    rel_err = np.abs(error_ms) / true_ms
    ratio_err = np.maximum(pred_ms / true_ms, true_ms / pred_ms)

    rmse_log = np.sqrt(mean_squared_error(y_log_true, y_log_pred))
    rmse_ms = np.sqrt(np.mean(error_ms ** 2))
    rmse_percent = np.sqrt(np.mean(((error_ms / true_ms) * 100) ** 2))

    return {
        "rmse_log": rmse_log,
        "rmse_ms": rmse_ms,
        "rmse_percent": rmse_percent,

        "median_relative_error": np.median(rel_err),
        "p90_relative_error": np.percentile(rel_err, 90),
        "p95_relative_error": np.percentile(rel_err, 95),

        "median_percent_error": np.median(rel_err) * 100,
        "p90_percent_error": np.percentile(rel_err, 90) * 100,
        "p95_percent_error": np.percentile(rel_err, 95) * 100,

        "median_ratio_error": np.median(ratio_err),
        "p90_ratio_error": np.percentile(ratio_err, 90),

        "within_10pct": np.mean(rel_err <= 0.10),
        "within_25pct": np.mean(rel_err <= 0.25),
        "within_50pct": np.mean(rel_err <= 0.50),
        "within_2x": np.mean(ratio_err <= 2.0),
    }

In [38]:
val_metrics = latency_metrics_from_log(y_val, final_model.predict(X_val))
test_metrics = latency_metrics_from_log(y_test, final_model.predict(X_test))

pd.DataFrame([val_metrics, test_metrics], index=["val", "test"])

,rmse_log,rmse_ms,rmse_percent,median_relative_error,p90_relative_error,p95_relative_error,median_percent_error,p90_percent_error,p95_percent_error,median_ratio_error,p90_ratio_error,within_10pct,within_25pct,within_50pct,within_2x
val,0.288527,163.981771,39.200427,0.083199,0.420502,0.592877,8.319857,42.050171,59.287650,1.087672,1.527444,0.553880,0.807802,0.925476,0.958898
test,0.283463,148.513679,35.851394,0.082335,0.420670,0.596226,8.233537,42.066966,59.622642,1.086706,1.528139,0.558674,0.808314,0.925383,0.959270

# Analysis

In [27]:
test_results = test_df.copy()

test_results["pred_log_latency"] = test_pred
test_results["true_log_latency"] = y_test

test_results["pred_latency_ms"] = np.exp(test_results["pred_log_latency"])
test_results["true_latency_ms"] = np.exp(test_results["true_log_latency"])

test_results["relative_error"] = (
    np.abs(test_results["pred_latency_ms"] - test_results["true_latency_ms"])
    / test_results["true_latency_ms"]
)

In [28]:
def group_latency_metrics(g):
    y_true = g["true_log_latency"].to_numpy()
    y_pred = g["pred_log_latency"].to_numpy()

    true_ms = np.exp(y_true)
    pred_ms = np.exp(y_pred)

    rel_err = np.abs(pred_ms - true_ms) / true_ms

    return pd.Series({
        "count": len(g),
        "rmse_log": np.sqrt(mean_squared_error(y_true, y_pred)),
        "within_10pct": np.mean(rel_err <= 0.10),
        "within_25pct": np.mean(rel_err <= 0.25),
        "within_50pct": np.mean(rel_err <= 0.50),
    })

In [29]:
test_results.groupby("platform").apply(group_latency_metrics).reset_index()

/tmp/ipykernel_7223/3061731483.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  test_results.groupby("platform").apply(group_latency_metrics).reset_index()

   platform    count  rmse_log  within_10pct  within_25pct  within_50pct
0  bluehive  10744.0  0.326154      0.537323      0.771593      0.896314
1    gcloud  10739.0  0.233054      0.580035      0.845051      0.954465

In [31]:
test_results.groupby(["machine_type", "platform"]).apply(group_latency_metrics).reset_index()

/tmp/ipykernel_7223/2224414100.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  test_results.groupby(["machine_type", "platform"]).apply(group_latency_metrics).reset_index()

,machine_type,platform,count,rmse_log,within_10pct,within_25pct,within_50pct
0,epyc,gcloud,9388.0,0.205541,0.602365,0.866745,0.965168
1,xeon,gcloud,1351.0,0.371710,0.424870,0.694301,0.880089
2,xeon_plat,bluehive,10744.0,0.326154,0.537323,0.771593,0.896314

In [33]:
test_results.groupby(["cpu_provider", "platform"]).apply(group_latency_metrics).reset_index()

/tmp/ipykernel_7223/3658681541.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  test_results.groupby(["cpu_provider", "platform"]).apply(group_latency_metrics).reset_index()

,cpu_provider,platform,count,rmse_log,within_10pct,within_25pct,within_50pct
0,amd,gcloud,9388.0,0.205541,0.602365,0.866745,0.965168
1,intel,bluehive,10744.0,0.326154,0.537323,0.771593,0.896314
2,intel,gcloud,1351.0,0.371710,0.424870,0.694301,0.880089

In [34]:
test_results.groupby(["cpu_provider", "platform", "num_cores"]).apply(
    group_latency_metrics,
    include_groups=False
).reset_index()

,cpu_provider,platform,num_cores,count,rmse_log,within_10pct,within_25pct,within_50pct
0,amd,gcloud,1,2636.0,0.156167,0.725341,0.924127,0.979135
1,amd,gcloud,2,4015.0,0.196945,0.596015,0.876214,0.973848
2,amd,gcloud,4,2737.0,0.254011,0.493241,0.797589,0.938984
3,intel,bluehive,1,1347.0,0.240651,0.633259,0.864143,0.947290
4,intel,bluehive,2,2686.0,0.262453,0.627699,0.836932,0.929635
5,intel,bluehive,4,3999.0,0.319717,0.533133,0.767942,0.896224
6,intel,bluehive,8,2712.0,0.416789,0.406342,0.666298,0.838127
7,intel,gcloud,6,1351.0,0.371710,0.424870,0.694301,0.880089